import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  safe: {
    flex: 1,
  },
  scroll: {
    padding: 20,
    paddingBottom: 80,
  },
  shell: {
    borderRadius: 28,
    padding: 18,
    borderWidth: 1,
    shadowColor: "#000",
    shadowOpacity: 0.35,
    shadowOffset: { width: 0, height: 14 },
    shadowRadius: 28,
    elevation: 10,
  },
  header: {
    alignItems: "center",
    gap: 10,
    marginBottom: 18,
  },
  title: {
    fontSize: 30,
    fontWeight: "900",
    textAlign: "center",
    letterSpacing: 1.5,
  },
  discreet: {
    textAlign: "center",
    marginTop: 4,
    opacity: 0.8,
  },
  badge: {
    paddingVertical: 10,
    paddingHorizontal: 16,
    borderRadius: 18,
    borderWidth: 1,
  },
  badgeText: {
    fontWeight: "800",
  },
  panel: {
    borderRadius: 18,
    padding: 12,
    borderWidth: 1,
    marginBottom: 14,
    gap: 10,
  },
  controls: {
    flexDirection: "row",
    gap: 12,
    flexWrap: "wrap",
  },
  control: {
    flex: 1,
    minWidth: 240,
    gap: 8,
  },
  label: {
    fontWeight: "800",
  },
  input: {
    borderWidth: 1,
    borderRadius: 12,
    padding: 12,
    fontSize: 16,
  },
  button: {
    borderWidth: 1,
    borderRadius: 12,
    paddingVertical: 14,
    alignItems: "center",
    shadowOpacity: 0.2,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 6 },
    elevation: 4,
  },
  buttonText: {
    fontWeight: "900",
    letterSpacing: 0.6,
  },
  buttonDisabled: {
    opacity: 0.65,
  },
  outline: {},
  outlineText: {},
  chips: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  chip: {
    borderRadius: 14,
    borderWidth: 1,
    flexBasis: "48%",
    alignItems: "center",
  },
  chipText: {
    fontWeight: "800",
  },
  chipTextSelecionado: {},
  chipSelecionado: {
    shadowOpacity: 0.25,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 6 },
    elevation: 3,
  },
  board: {
    borderRadius: 22,
    padding: 16,
    borderWidth: 1,
    shadowColor: "#000",
    shadowOpacity: 0.3,
    shadowOffset: { width: 0, height: 12 },
    shadowRadius: 20,
    elevation: 8,
  },
  grid: {
    flexDirection: "row",
    flexWrap: "wrap",
    borderRadius: 16,
    padding: 12,
    alignSelf: "center",
  },
  cell: {
    borderRadius: 16,
    borderWidth: 2,
    alignItems: "center",
    justifyContent: "center",
    shadowColor: "#000",
    shadowOpacity: 0.25,
    shadowOffset: { width: 0, height: 6 },
    shadowRadius: 12,
    elevation: 4,
  },
  cellSpinning: {
    opacity: 0.8,
  },
  cellText: {
    fontSize: 24,
  },
  status: {
    marginTop: 12,
    flexDirection: "row",
    justifyContent: "space-between",
    flexWrap: "wrap",
    gap: 10,
  },
  statCard: {
    flexGrow: 1,
    minWidth: 120,
    paddingVertical: 10,
    paddingHorizontal: 12,
    borderRadius: 14,
    borderWidth: 1,
  },
  statLabel: {
    fontWeight: "700",
    marginBottom: 4,
  },
  statValue: {
    fontWeight: "900",
    fontSize: 16,
  },
  message: {
    marginTop: 12,
    borderRadius: 14,
    padding: 12,
    borderWidth: 2,
    alignItems: "center",
  },
  messageText: {
    fontWeight: "700",
    textAlign: "center",
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.45)",
    alignItems: "center",
    justifyContent: "center",
    padding: 20,
  },
  modalBox: {
    width: "100%",
    borderRadius: 18,
    padding: 16,
    borderWidth: 1,
    gap: 12,
  },
  modalTitle: {
    textAlign: "center",
    fontSize: 18,
    fontWeight: "900",
  },
  modalSubtitle: {
    textAlign: "center",
    fontWeight: "700",
  },
  modalActions: {
    flexDirection: "row",
    gap: 10,
  },
  configRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  configLabel: {
    fontWeight: "700",
  },
  bottomBar: {
    position: "absolute",
    bottom: 20,
    left: 20,
    right: 20,
    borderRadius: 16,
    paddingVertical: 10,
    paddingHorizontal: 14,
    borderWidth: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    shadowColor: "#000",
    shadowOpacity: 0.2,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 6 },
    elevation: 6,
  },
  exitButton: {
    borderRadius: 14,
    paddingVertical: 12,
    paddingHorizontal: 26,
    alignItems: "center",
    borderWidth: 1,
  },
  exitButtonText: {
    fontWeight: "800",
    letterSpacing: 0.6,
  },
  iconButton: {
    width: 46,
    height: 46,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
  },
  bottomIcon: {
    fontSize: 22,
  },
});

